alias: 'Turn on the Christmas Tree if there is occupancy'
trigger:
  - platform: state
    entity_id:
      - group.occupancy
condition:
  - condition: time
    after: '06:00:00'
    before: '22:30:00'
action:
  - service_template: "light.turn_{{ trigger.to_state.state }}"
    entity_id: light.smart_switch
  - service_template: "light.turn_{{ trigger.to_state.state }}"
    entity_id: light.wemo_mini
