alias: 'Turn the Christmas Tree off at 23:01:00'
trigger:
  - platform: time
    hours: 23
    minutes: 01
    seconds: 00
action:
  - service: switch.turn_off
    entity_id: switch.smart_switch_6_tree
