alias: 'Turn the Christmas Tree off at 22:31:00'
trigger:
  - platform: time
    hours: 22
    minutes: 31
    seconds: 00
action:
  - service: light.turn_off
    entity_id: light.smart_switch
  - service: light.turn_off
    entity_id: light.wemo_mini
