alias: 'Garage Relay normally open'
trigger:
  - platform: time
    seconds: '/5'
condition:
  - condition: state
    entity_id: !secret zwave_switch_garage_relay
    state: "on"
action:
  - service: switch.turn_off
    data_template:
      entity_id: !secret zwave_switch_garage_relay