alias: 'Garage Relay normally open'
trigger:
  - platform: time
    seconds: '/5'
condition:
  - condition: state
    entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_4_0
    state: "on"
action:
  - service: switch.turn_off
    data_template:
      entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_4_0
