alias: 'Garage Relay normally open'
trigger:
  - platform: time_pattern
    seconds: '/5'
condition:
  - condition: state
    entity_id: switch.relay_garage_door
    state: "on"
action:
  - service: switch.turn_off
    data_template:
      entity_id: switch.relay_garage_door
