alias: 'Notify if sensors change when nobody is home'
trigger:
  - platform: state
    entity_id:
      - binary_sensor.ecolink_doorwindow_sensor_sensor_5
      - binary_sensor.ecolink_doorwindow_sensor_sensor_6
      - sensor.everspring_st812_flood_detector_flood_2
      - switch.linear_fs20z_isolated_contact_fixture_module_switch_4
      - switch.ge_12727_inwall_smart_switch_toggle_switch_7
      - binary_sensor.ecolink_garage_door_sensor_sensor_3
    from: 'off'
    to: 'on'
condition:
  condition: state
  entity_id: group.all_devices
  state: 'not_home'
action:
  - service: notify.html5_scott_phone
    data_template:
      title: "Alarm!"
      message: "The {{ trigger.to_state.name }} was changed to {{ trigger.to_state.state }} while no one is home. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"