alias: 'Notify if sensors change when nobody is home'
trigger:
  - platform: state
    entity_id:
      - binary_sensor.door_side
      - binary_sensor.door_front
      - binary_sensor.door_garage
      - binary_sensor.ecobee_occupancy
      - binary_sensor.living_room_occupancy
      - binary_sensor.master_bedroom_occupancy
      - binary_sensor.office_occupancy
      - switch.relay_garage_door
      - switch.light_side_entry
    from: 'off'
    to: 'on'
condition:
  condition: state
  entity_id: group.all_devices
  state: 'not_home'
action:
  - service: notify.html5_scott_phone
    data_template:
      title: "Alarm!"
      message: "The {{ trigger.to_state.name }} was changed to {{ trigger.to_state.state }} while no one is home. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
