alias: 'Notify if sensors change when nobody is home'
trigger:
  - platform: state
    entity_id:
      - !secret zwave_door_front
      - !secret zwave_door_side
      - !secret zwave_flood
      - !secret zwave_switch_garage_relay
      - !secret zwave_switch_side_entry_light
      - !secret zwave_tilt_garage
    from: 'off'
    to: 'on'
condition:
  condition: state
  entity_id: group.all_devices
  state: 'not_home'
action:
  - service: notify.html5_scott_phone
    data_template:
      title: "Alarm!"
      message: "The {{ trigger.to_state.name }} was changed to {{ trigger.to_state.state }} while no one is home. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"