alias: 'Notify Update Available'
trigger:
  - platform: state
    entity_id: updater.updater
  - platform: event
    event_type: homeassistant_start
condition:
  - condition: template
    value_template: "{{ states('updater.updater') != 'unknown' }}"
action:
  - service: notify.html5
    data_template:
      title: "Update Available"
      message: "Home Assistant {{ states('updater.updater') }} is available. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
      data:
        url: "https://www.home-assistant.io/hassio/#upgrading"
  - service: persistent_notification.create
    data:
      title: "Update Available"
      message: >
        Home Assistant [update](https://www.home-assistant.io/hassio/#upgrading) {{ states('updater.updater') }} is available. - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}
      notification_id: "update_available"