alias: 'Turn on the side entry light if the door opens after sunset'
trigger:
  - platform: state
    entity_id: binary_sensor.door_side
    from: 'off'
    to: 'on'
condition:
  - condition: sun
    after: sunset
action:
  - service: switch.turn_on
    entity_id: switch.light_side_entry
