alias: 'Turn on the side entry light if the door opens after sunset'
trigger:
  - platform: state
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor_5
    from: 'off'
    to: 'on'
condition:
  - condition: sun
    after: sunset
action:
  - service: switch.turn_on
    entity_id: switch.ge_12727_inwall_smart_switch_toggle_switch_7